### PR TITLE
Supercasey 2015 updates and new kinds of data with carls new tests

### PR DESCRIPTION
**Pull request by cschroedl-gov**
Not sure we should merge this. I wanted to see what you thought of some potential new tests and their output. The tests build a set of unique qw site ids for each data frame and they compare each set against a reference set of qw site ids. I somewhat arbitrarily chose aflow's qw site ids as the reference set. Should we be ensuring that the same sites are present across data frames? If so, which ones should be consistent?

```
==> devtools::test()

Loading nardata
Loading required package: testthat
Testing nardata

Attaching package: ‘validate’

The following object is masked from ‘package:testthat’:

    compare

all time series : ...........[1] "using 116 sites from dataframe ' aflow ' as the reference site list"
123456789a
annual flow : ......
annual load : .........
pesticide benchmark : ...
daily flow : ......
discrete water quality : .......
may flow : ......
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

..
may load : .........
non-pesticide time series : .
pesticide 21 day moving average data : ....
pesticide 60 day moving average data : ....
pesticide sample data : .....
pesticide site summary data : ...
pesticide annual weighted average data : .....
pesticide long name : ...

1. Failure: the same sites are present in all time series data frames ----------
The following 2 sites were in the reference site list, but not in ' aloads '. 
 01054200, 11206800 

 The following 3 sites were in ' aloads ', but not in the reference sites. 
 03612500, GULF, MISS

2. Failure: the same sites are present in all time series data frames ----------
The following 0 sites were in the reference site list, but not in ' dflow '. 


 The following 10 sites were in ' dflow ', but not in the reference sites. 
 02172300, 02470500, 03612500, 05014300, 05587450, 06324970, 07055646, 08227000, 09471000, 11335000

3. Failure: the same sites are present in all time series data frames ----------
The following 0 sites were in the reference site list, but not in ' discqw '. 


 The following 1 sites were in ' discqw ', but not in the reference sites. 
 05014300

4. Failure: the same sites are present in all time series data frames ----------
The following 82 sites were in the reference site list, but not in ' mflow '. 
 01054200, 01170100, 01184000, 01209710, 01349150, 01372043, 01435000, 01463500, 01466500, 01545600, 01578310, 01610400, 01646580, 01654000, 02087580, 02089500, 02091500, 02175000, 02226160, 02327100, 02335870, 02338000, 02338523, 02359170, 02429500, 02469762, 03497300, 04063700, 04161820, 04193500, 04264331, 05082500, 05124480, 05288705, 05451210, 06713500, 06775900, 06800000, 07060710, 07288650, 08014500, 08057200, 08057410, 08116650, 08195000, 08364000, 08475000, 09163500, 09196500, 09352900, 09380000, 09505800, 09522000, 10168000, 10171000, 10172200, 10343500, 10350340, 11074000, 11206800, 11264500, 11274538, 11303500, 11447650, 12056500, 12447390, 12505450, 12510500, 13056500, 13092747, 13154500, 14161500, 14201300, 14205400, 14206950, 14211720, 14246900, 15292700, 15565447, 16618000, 394340085524601, 402114105350101 

 The following 1 sites were in ' mflow ', but not in the reference sites. 
 GULF

5. Failure: the same sites are present in all time series data frames ----------
The following 82 sites were in the reference site list, but not in ' mloads '. 
 01054200, 01170100, 01184000, 01209710, 01349150, 01372043, 01435000, 01463500, 01466500, 01545600, 01578310, 01610400, 01646580, 01654000, 02087580, 02089500, 02091500, 02175000, 02226160, 02327100, 02335870, 02338000, 02338523, 02359170, 02429500, 02469762, 03497300, 04063700, 04161820, 04193500, 04264331, 05082500, 05124480, 05288705, 05451210, 06713500, 06775900, 06800000, 07060710, 07288650, 08014500, 08057200, 08057410, 08116650, 08195000, 08364000, 08475000, 09163500, 09196500, 09352900, 09380000, 09505800, 09522000, 10168000, 10171000, 10172200, 10343500, 10350340, 11074000, 11206800, 11264500, 11274538, 11303500, 11447650, 12056500, 12447390, 12505450, 12510500, 13056500, 13092747, 13154500, 14161500, 14201300, 14205400, 14206950, 14211720, 14246900, 15292700, 15565447, 16618000, 394340085524601, 402114105350101 

 The following 4 sites were in ' mloads ', but not in the reference sites. 
 03612500, 7373420, GULF, MISS

6. Failure: the same sites are present in all time series data frames ----------
The following 38 sites were in the reference site list, but not in ' pest21day '. 
 01054200, 01170100, 01435000, 01466500, 01545600, 01610400, 02327100, 02338523, 02429500, 03086000, 03497300, 03612600, 04063700, 05124480, 06775900, 06902000, 06926510, 07060710, 07355500, 08014500, 08195000, 09196500, 09352900, 09505800, 10172200, 10343500, 11206800, 11264500, 11274538, 12056500, 12447390, 13056500, 14161500, 14205400, 15292700, 15565447, 16618000, 402114105350101 

 The following 1 sites were in ' pest21day ', but not in the reference sites. 
 03612500

7. Failure: the same sites are present in all time series data frames ----------
The following 38 sites were in the reference site list, but not in ' pest60day '. 
 01054200, 01170100, 01435000, 01466500, 01545600, 01610400, 02327100, 02338523, 02429500, 03086000, 03497300, 03612600, 04063700, 05124480, 06775900, 06902000, 06926510, 07060710, 07355500, 08014500, 08195000, 09196500, 09352900, 09505800, 10172200, 10343500, 11206800, 11264500, 11274538, 12056500, 12447390, 13056500, 14161500, 14205400, 15292700, 15565447, 16618000, 402114105350101 

 The following 1 sites were in ' pest60day ', but not in the reference sites. 
 03612500

8. Failure: the same sites are present in all time series data frames ----------
The following 14 sites were in the reference site list, but not in ' pestsamp '. 
 01054200, 01545600, 02429500, 03497300, 03612600, 05124480, 09196500, 09352900, 10343500, 11206800, 12447390, 14161500, 15292700, 16618000 

 The following 1 sites were in ' pestsamp ', but not in the reference sites. 
 03612500

9. Failure: the same sites are present in all time series data frames ----------
The following 35 sites were in the reference site list, but not in ' pestsites '. 
 01054200, 01170100, 01435000, 01466500, 01545600, 01610400, 02327100, 02338523, 02429500, 03086000, 03497300, 03612600, 04063700, 05124480, 06775900, 06902000, 06926510, 07060710, 07355500, 08014500, 08195000, 09196500, 09352900, 09505800, 10172200, 10343500, 11206800, 11264500, 12056500, 12447390, 14161500, 14205400, 15292700, 16618000, 402114105350101 

 The following 2 sites were in ' pestsites ', but not in the reference sites. 
 02428400, 03612500

a. Failure: the same sites are present in all time series data frames ----------
The following 39 sites were in the reference site list, but not in ' pestweightave '. 
 01054200, 01170100, 01435000, 01466500, 01545600, 01610400, 02327100, 02338000, 02338523, 02429500, 03086000, 03497300, 03612600, 04063700, 05124480, 06775900, 06902000, 06926510, 07060710, 07355500, 08014500, 08195000, 09196500, 09352900, 09505800, 10172200, 10343500, 11206800, 11264500, 11274538, 12056500, 12447390, 13056500, 14161500, 14205400, 15292700, 15565447, 16618000, 402114105350101 

 The following 1 sites were in ' pestweightave ', but not in the reference sites. 
 03612500
Warning messages:
1: In left_join_impl(x, y, by$x, by$y) :
  joining factors with different levels, coercing to character vector
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
```

### CODE REVIEW

**Comment by cschroedl-gov** [comment]
This all came about because I noticed inconsistency between the set of site qw ids in pestsites and pestsamp:

```
#demonstration of the setdiff function
setdiff(c(1,2,3), c(1,2,4))
[1] 3
> setdiff(c(1,2,4), c(1,2,3))
[1] 4
#applying setdiff to two pesticide data frames
> setdiff(unique(pestsamp$SITE_QW_ID), unique(pestsites$SITE_QW_ID))
 [1] "01170100"        "01435000"        "01466500"        "01610400"        "02327100"        "02338523"        "03086000"       
 [8] "04063700"        "06775900"        "06902000"        "06926510"        "07060710"        "07355500"        "08014500"       
[15] "08195000"        "09505800"        "10172200"        "11264500"        "12056500"        "14205400"        "402114105350101"
> setdiff(unique(pestsites$SITE_QW_ID), unique(pestsamp$SITE_QW_ID))
[1] "02428400"
```

In the data's current state, the site qw ids that appear in pestsamp but do not appear in pestsite will not be discoverable by the web app (neither downloadable or visualizable), because the time series data in pestsamp has no record of the most frequently detected herbicides or non-herbicides in pestsamp.

**Comment by supercasey** [comment]
Thanks Carl, this is a good idea.  I think the most important thing will be to make sure that the site qw ids from the data are in the reference list, not the other way around.  The reason for this is that even though we have a site in the network, there may not yet be adequate data at that site to compute a load or to display pesticide concentrations.  So I think we should keep the tests that check that the qw site ids from the data are in the reference list, but not the other comparisons.  Make sense?

**Comment by cschroedl-gov** [comment]
Also, should we build our code to handle cases like site 02428400, where there is a pestsites record, but there isn't any time series data for it in pestsamp?

**Comment by cschroedl-gov** [comment]
Thanks for the feedback Casey. I like that idea. We don't have a reference site list in this repo. Can we use the network's shapefile as the reference site list?

**Comment by supercasey** [comment]
Yep, I think that would be a good idea.  The pestsites dataframe should serve as the reference list for all of the pesticide data, but sites within pestsites should also be present in the overall reference sitelist.  This is because we have an overall sitelist (obtained from the shapefile), some sites which have (or will have) pesticide data (the pestsites dataframe), and then the data itself.

**Comment by supercasey** [comment]
I resolved the issues you brought up with the data and will make another pull request for the data in a few minutes.  However one exception to this test is that for the mloads and aloads files, there will be some loads that have SITE_QW_IDS of "GULF" and "MISS", which we need, but will not be in the shapefile.  I can edit these tests if you want, just not sure if I'll get to it until the week of August 8.

**Comment by cschroedl-gov** [comment]
Thanks Casey! Good discussion.

**Pull request closed without merging**
